;;; workspaces-tests.el --- Tests for workspaces -*- lexical-binding: t; -*-

(require 'ert)
(require 'workspaces)

(ert-deftest workspaces-local-buffer-exclusion-takes-precedence ()
  (with-temp-buffer
    (rename-buffer "workspaces-test-buffer" t)
    (let ((workspaces-include-buffers (list (buffer-name)))
          (workspaces-exclude-buffers (list (buffer-name))))
      (should-not (workspaces--local-buffer-p (current-buffer))))))

(ert-deftest workspaces-buffer-list-restores-from-public-window-state ()
  (with-temp-buffer
    (rename-buffer "workspaces-state-buffer" t)
    (let ((buffer (current-buffer))
          (state (save-window-excursion
                   (switch-to-buffer (current-buffer))
                   (window-state-get))))
      (cl-letf (((symbol-function 'workspaces--tabs)
                 (lambda (&optional _frame)
                   `((tab (name . "hidden") (ws . ,state))))))
        (should (memq buffer (workspaces--buffer-list nil 0)))))))

(ert-deftest workspaces-switch-buffer-does-not-mutate-tab-lists ()
  (let ((first (get-buffer-create "workspaces-first"))
        (second (get-buffer-create "workspaces-second"))
        switched-tab
        switched-buffer
        prompted)
    (unwind-protect
        (cl-letf (((symbol-function 'workspaces--list)
                   (lambda () '("one" "two")))
                  ((symbol-function 'workspaces--tab-index-by-name)
                   (lambda (name &optional _frame)
                     (if (equal name "one") 0 1)))
                  ((symbol-function 'workspaces--buffer-list)
                   (lambda (&optional _frame index)
                     (if (= index 0) (list first) (list second))))
                  ((symbol-function 'tab-bar-switch-to-tab)
                   (lambda (name) (setq switched-tab name)))
                  ((symbol-function 'workspaces-switch-to-buffer)
                   (lambda (buffer &rest _args)
                     (setq switched-buffer buffer)))
                  ((symbol-function 'completing-read)
                   (lambda (&rest _args)
                     (setq prompted t))))
          (workspaces-switch-buffer-and-tab (buffer-name second))
          (should (equal switched-tab "two"))
          (should (equal switched-buffer (buffer-name second)))
          (should-not prompted))
      (kill-buffer first)
      (kill-buffer second))))

(ert-deftest workspaces-switches-live-unassigned-buffer-in-current-tab ()
  (let ((buffer (get-buffer-create "workspaces-unassigned"))
        switched)
    (unwind-protect
        (cl-letf (((symbol-function 'workspaces--list) (lambda () '("one")))
                  ((symbol-function 'workspaces--tab-index-by-name)
                   (lambda (&rest _args) 0))
                  ((symbol-function 'workspaces--buffer-list)
                   (lambda (&rest _args) nil))
                  ((symbol-function 'workspaces-switch-to-buffer)
                   (lambda (name &rest _args) (setq switched name))))
          (workspaces-switch-buffer-and-tab (buffer-name buffer))
          (should (equal switched (buffer-name buffer))))
      (kill-buffer buffer))))

(ert-deftest workspaces-restores-existing-frame-buffer-predicate ()
  (let* ((frame (selected-frame))
         (original (frame-parameter frame 'buffer-predicate))
         (saved (lambda (_buffer) 'saved)))
    (unwind-protect
        (progn
          (set-frame-parameter frame 'buffer-predicate saved)
          (workspaces--set-buffer-predicate frame)
          (should-not (eq (frame-parameter frame 'buffer-predicate) saved))
          (workspaces--reset-buffer-predicate frame)
          (should (eq (frame-parameter frame 'buffer-predicate) saved)))
      (set-frame-parameter frame 'buffer-predicate original)
      (remhash frame workspaces--frame-buffer-predicates))))

(ert-deftest workspaces-open-switches-tab-before-project ()
  (let (events)
    (cl-letf (((symbol-function 'project-known-project-roots)
               (lambda () '("/tmp/workspaces-project/")))
              ((symbol-function 'workspaces--list)
               (lambda () '("/tmp/workspaces-project/")))
              ((symbol-function 'tab-bar-switch-to-tab)
               (lambda (_name) (push 'tab events)))
              ((symbol-function 'project-switch-project)
               (lambda (_directory) (push 'project events))))
      (workspaces-open "/tmp/workspaces-project/")
      (should (equal (nreverse events) '(tab project))))))

(ert-deftest workspaces-close-preserves-buffers-shared-with-other-tabs ()
  (let ((shared (get-buffer-create "workspaces-shared"))
        (unique (get-buffer-create "workspaces-unique"))
        closed)
    (unwind-protect
        (cl-letf (((symbol-function 'workspaces--list)
                   (lambda () '("target" "other")))
                  ((symbol-function 'workspaces--tab-index-by-name)
                   (lambda (name &optional _frame)
                     (if (equal name "target") 0 1)))
                  ((symbol-function 'workspaces--buffer-list)
                   (lambda (&optional _frame index)
                     (if (= index 0) (list shared unique) (list shared))))
                  ((symbol-function 'tab-bar-close-tab-by-name)
                   (lambda (name) (setq closed name))))
          (workspaces-close "target")
          (should (buffer-live-p shared))
          (should-not (buffer-live-p unique))
          (should (equal closed "target")))
      (when (buffer-live-p shared)
        (kill-buffer shared))
      (when (buffer-live-p unique)
        (kill-buffer unique)))))

(ert-deftest workspaces-read-directory-refuses-missing-directory ()
  (cl-letf (((symbol-function 'read-directory-name)
             (lambda (&rest _args) "/does/not/exist/"))
            ((symbol-function 'file-directory-p) (lambda (_dir) nil))
            ((symbol-function 'y-or-n-p) (lambda (_prompt) nil)))
    (should-error (workspaces--read-directory-name "Directory: ")
                  :type 'user-error)))

(provide 'workspaces-tests)
;;; workspaces-tests.el ends here
